[build]
  command = "npm --prefix templetehelpline install && npm --prefix templetehelpline run build"
  publish = "templetehelpline/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
